### ISSUE TITLE
It seem auto generated type not recognized relation

### ISSUE THREAD

**Issue by namttdh** [LastDragon-ru/lara-asp#135] opened 2024-02-27 20:35 UTC
This our my query
```
extend type Query {
    getOrders(where: _ @searchBy): [Order]! @paginate
}
```
Order type
```
type Order {
    "Unique primary key."
    id: ID!

    code: String

    status: OrderStatusConst

    payment_method: String

    user: User @belongsTo

    orderBill: OrderBill @hasOne

    shop: Shop @belongsTo

    orderShip: OrderShip @hasOne

    orderItems: [OrderItem] @hasMany

    orderHistories: [OrderHistory] @hasMany

    shippingCarrier: ShippingCarrier @hasOne
}

enum OrderStatusConst {
    PENDING
    PROCESSING
    SHIPPING
    DELIVERED
    CANCELED
}

```

Generate type 
![image](https://github.com/LastDragon-ru/lara-asp/assets/30091962/97e8aed0-a846-4775-8fa2-8c35e1a49f0b)

=> It seem missing relation type, i don't know why, could you check it?

**Comment by namttdh** [comment] 2024-02-27 20:41
Hmm, maybe we need add RelationDirective::class in the config file?

```diff
'builder'   => [
        /**
         * The list of the directives which should be copied from the original
         * field into the generated `input` field. All other directives except
         * {@see Operator} will be ignored.
         *
         * The `instanceof` operator is used to check.
         */
        'allowed_directives' => [
            RenameDirective::class,
            + Nuwave\Lighthouse\Schema\Directives\RelationDirective::class,
        ],
    ],
```

**Comment by LastDragon-ru** [comment] 2024-02-28 04:34
> It seem missing relation type, i don't know why, could you check it?

This is known issue in v5, it should be fixed in `main` (v6). So maybe you can try it? (see also [Upgrade Guide](https://github.com/LastDragon-ru/lara-asp/blob/main/packages/graphql/UPGRADE.md))

> Added and it work like a champp.

Please note that it will not work in `main` (v6). Another way

```
user: User @belongsTo @searchByOperatorRelation
```

**Comment by namttdh** [comment] 2024-02-28 09:40
It really really hard code for this way..
```
user: User @belongsTo @searchByOperatorRelation
```
I think i'll update to [dev-main](https://packagist.org/packages/lastdragon-ru/lara-asp-graphql#dev-main) to testing it.

Btw, i'm also seeking for schema generation from model PHPDocs, try define both Eloquent Model and graphql type kinda bored...

**Comment by LastDragon-ru** [comment] 2024-02-29 04:30
Probably you need to set `"minimum-stability": "dev"` in your `composer.json`.

**Comment by LastDragon-ru** [comment] 2024-03-26 07:20
I hope the issue is not actual in v6, so will close this :)

**Closed by LastDragon-ru** 2024-03-26 07:20 UTC
Labels: bug, pkg: graphql
